spring.application.name=Watchly

# =========================================
# DATABASE (POSTGRESQL)
# =========================================

spring.datasource.url=jdbc:postgresql://localhost:5432/watchly
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================================
# JPA / HIBERNATE
# =========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================================
# SQL INIT
# =========================================

spring.sql.init.mode=always

# =========================================
# SERVER
# =========================================

server.port=8080

# =========================================
# JWT
# =========================================

jwt.secret=MinhaChaveMuitoGrandeComMaisDe32Caracteres123456
jwt.expiration=86400000

# =========================================
# LOGGING
# =========================================

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE