spring.application.name=Watchly

# =========================================
# DATABASE
# =========================================

spring.datasource.url=jdbc:postgresql://localhost:5432/watchly
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver


# =========================================
# JPA / HIBERNATE
# =========================================

spring.jpa.hibernate.ddl-auto=update

# opções:
# create       -> recria o banco toda vez
# create-drop  -> recria e apaga ao finalizar
# update       -> atualiza automaticamente
# validate     -> apenas valida
# none         -> desativa

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# =========================================
# SQL INIT
# =========================================

spring.sql.init.mode=always


# =========================================
# SERVER
# =========================================

server.port=8080


# =========================================
# LOGGING
# =========================================

logging.level.org.hibernate.SQL=DEBUG

logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE